import Link from 'next/link'
import Head from 'next/head'


export default  function MainLayout  ({children,title = "NextJS"}) {
    return (
        <>
        <Head>
            <title>{title}</title>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <nav>
        <Link href={'/'}><a>Home</a></Link>
        <Link href={'/users'}><a>Users</a></Link>
        <Link href={'/users/111'}><a>Users 111</a></Link>
        </nav>
        <main>
            {children}
        </main>
        </>
    )
} 